---
title: "cellcomp_analysis"
output: html_document
date: "2023-12-08"
---

```{r}
library(compositions)
library(robCompositions)
library(tidyverse)
library(planet)
library(qgcomp)
#reading in pheno and BMIQ 
load("2_BMIQ_Adjsuted.RData")
load("ALLBETAS.FunNormBMIQ.RData")
colnames(FunNorm.BMIQ.ALL) = pd$Sample_Name

load("/Users/cynthiaperez/WGCNA_PFAS/log_PFAS_pheno.Rdata")
## Drop the two samples that weren't run (G-155 & G-157):
# Get the intersection of column names to keep
cols_to_keep <- intersect(colnames(FunNorm.BMIQ.ALL), rownames(log_pfas))

# Subset FunNorm.BMIQ.ALL to keep only the columns present in cols_to_keep
FunNorm.BMIQ.ALL <- FunNorm.BMIQ.ALL[, cols_to_keep]

pheno <- pheno[colnames(FunNorm.BMIQ.ALL),]
log_pfas <- log_pfas[colnames(FunNorm.BMIQ.ALL),]
```

```{r}
pheno <- pheno[colnames(FunNorm.BMIQ.ALL),]
pheno$RPC_clock = predictAge(FunNorm.BMIQ.ALL, type = "RPC")
pheno$CPC_clock = predictAge(FunNorm.BMIQ.ALL, type = "CPC")
pheno$RRPC_clock = predictAge(FunNorm.BMIQ.ALL, type = "RRPC")


pheno$RPC_lm_residuals = summary(lm(RPC_clock~gest_age_in_weeks_edd, pheno))$residuals
pheno$RRPC_lm_residuals = summary(lm(RRPC_clock~gest_age_in_weeks_edd, pheno))$residuals
pheno$CPC_lm_residuals= summary(lm(CPC_clock~gest_age_in_weeks_edd, pheno))$residuals

PFASp = c("L-PFOA","PFHxS","PFNA","PFDA","s-PFOS")
pheno = cbind(pheno, log_pfas[,PFASp])
colnames(pheno)[56] = "PFOA"
colnames(pheno)[60] = "PFOS"


cells <- c("Trophoblasts", "Stromal", "Hofbauer", "Endothelial", "nRBC", "Syncytiotrophoblast")
cell_comp <- pheno[,cells]

# round proportions less than pre-specified cutoff to zero

cutoff <- 10^-4
DL <- matrix(0,ncol=ncol(cell_comp),nrow=1)

  for(c in 1:ncol(cell_comp)){
    zeros_idx <- which(cell_comp[,c] < cutoff)
    if(length(zeros_idx) > 0){
      # round zeros, set DL to smallest non-zero value after rounding
      cell_comp[zeros_idx,c] <- 0
      DL[c] <- min(cell_comp[-zeros_idx,c])
    }
  }
  
# impute rounded zeros using detection limit
imp <- robCompositions::imputeBDLs(cell_comp, dl=DL,maxit=50,eps=0.1,R=50,method="pls", variation=F)
cell_comp_imp <- imp$x
rownames(cell_comp) <- rownames(pheno)
cell_comp_imp$participant_id <- rownames(cell_comp)
  
# construct data set for compositional regression
comp_data <- merge(pheno[,c("participant_id", "childs_sex","MomBMI_10wks", "MomBMI_12wks","MomBMI_36wks", "CPC_lm_residuals", "mom_age_at_birth", "mom_education", "official_enroll_category", "gest_age_in_weeks_edd", "PFOA", "PFHxS", "PFNA", "PFDA", "PFOS")], cell_comp_imp, by='participant_id') 

cell_types <- colnames(cell_comp)
cell_df_f= data.frame()
outcome <- compositions::acomp(comp_data[which(comp_data$childs_sex == "Female"),cell_types])
for ( i in c("PFOA","PFHxS","PFNA","PFDA","PFOS")){
  comp_mod <- lm(paste0("compositions::ilr(outcome) ~", i,"+ mom_age_at_birth + mom_education +  MomBMI_36wks  + MomBMI_10wks + official_enroll_category + gest_age_in_weeks_edd"), data= comp_data[which(comp_data$childs_sex == "Female"),])
  df = data.frame(pfas = i, p_value_PFAS = anova(comp_mod)[paste0(i),6])
  cell_df_f = rbind(cell_df_f, df)
}

```

```{r}
compositions::ilrInv(coef(comp_mod), orig=outcome)

pheno1 = merge(pheno, cell_comp, by = cells , all.x = TRUE)

PFAS_cell_comp = data.frame()

#pheno = pheno %>% filter(.$CPC_lm_residuals > -0.01)
for (i in c("PFOA","PFHxS","PFNA","PFDA","PFOS")) {
  model = lm(paste0("CPC_lm_residuals~", i,"+ Trophoblasts + Stromal + Hofbauer + Endothelial + nRBC + Syncytiotrophoblast"), data = pheno1[which(pheno1$childs_sex == "Male")])
  lm_summary <- summary(model)
  p_value <- lm_summary$coefficients[2,4]
  estimate <- coef(model)[2]
  df = data.frame(p.value = p_value, estimate = estimate,  PFAS = i)
  PFAS_cpc_lm= rbind(PFAS_cpc_lm, df)
}

PFAS_cell_comp
```

